security:
  oauth2:
    client:
      clientId: sender-service
      clientSecret: ${SENDER_SERVICE_PASSWORD:password}
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  port: 8100

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  mail:
    host: smtp.gmail.com
    port: 465
    username: dolgikhdanil4test@gmail.com
    password: hhwm bkqq vpwj gknc
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true

remind:
  email:
    text: "Hey, {0}! We''ve missed you here on PiggyMetrics. It''s time to check your budget statistics.\r\n\r\nCheers,\r\nPiggyMetrics team"
    subject: PiggyMetrics reminder

backup:
  email:
    text: "Howdy, {0}. Your account backup is ready.\r\n\r\nCheers,\r\nPiggyMetrics team"
    subject: PiggyMetrics account backup
    attachment: backup.json
